---
# File: .github/dependabot.yml
# Docs: https://docs.github.com/en/code-security/dependabot

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - groveld

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    assignees:
      - groveld
